version: '3'
services:

  wordpress:
    build: ./docker/wordpress
    volumes:
      - .:/var/www/html
    ports:
      - '8000:80' 
    restart: always
    depends_on:
      - mysql
    env_file: .envrc
    networks:
      - backend

  mysql:
    image: mysql:5.6
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3306:3306'
    restart: always
    env_file: .envrc
    networks:
      - backend

volumes:
  db:

networks:
  backend:
